### PR TITLE
Fix openBSD-builds (untested)

### PR DESCRIPTION
**Pull request by msirringhaus**

### CODE REVIEW

**Comment by landryb** [comment]
ping @reyk since you wrote the original code to support OpenBSD.. in my very limited testing here, seems that it builds within mozilla-central.

**Comment by msirringhaus** [comment]
Lemme quickly push an updated version, as I just saw that I need to do some changes, I tried to avoid at first, after all (because of netBSD and freeBSD). I'll probably add netBSD and freeBSD-fixes to this PR as well, once I have them.

**Comment by jschanck** [comment]
How are we going to test the netbsd and freebsd builds?

**Comment by msirringhaus** [comment]
For freeBSD and netBSD we can at least cross-compile. There seems to be no openBSD-target in rustup. 
It can't run the binary, obviously, but the build at least gets checked.

**Comment by landryb** [comment]
yes there's no rustup for OpenBSD, because it expects backwards-compatible ABI that isnt guaranteed for us.

**Review by jschanck — APPROVED** [review]
OK, it looks like this fixes the build errors and gives us something that we can iterate on. I'll cut a new release. Thanks!

**Pull request merged**
